version: "3.3"
services:
    redis:
        image: redis
        ports:
            - "6379:6379"

    postgres:
        env_file:
            - ./env/docker/.db.env
        ports:
            - "5432:5432"
        image: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 5s
            retries: 5

    pgadmin4:
        env_file:
            - ./env/docker/.db.env
        ports:
            - "8080:80"
        image: dpage/pgadmin4

    migration:
        depends_on:
            postgres:
                condition: service_healthy
        build:
            dockerfile: Dockerfile.migration
        env_file:
            - ./env/docker/.backend.env

    backend:
        healthcheck:
            test: ["CMD-SHELL", "curl -f -X HEAD http://backend:3001/ping"]
            interval: 30s
            timeout: 5s
            retries: 10
        depends_on:
            postgres:
                condition: service_healthy
            migration:
                condition: service_completed_successfully
        build:
            dockerfile: Dockerfile.backend
        env_file:
            - ./env/docker/.backend.env
        ports:
            - "3001:3001"
    
    frontend:
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://frontend:3000"]
            interval: 30s
            timeout: 5s
            retries: 10
        build:
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"
        env_file:
            - ./env/docker/.frontend.env