FROM node:20.5.1-slim

WORKDIR /app

RUN mkdir -p /app/backend
RUN mkdir -p /app/frontend

COPY package.json /app
COPY yarn.lock /app
COPY backend/package.json /app/backend

RUN yarn install 

COPY . /app

CMD yarn backend:migrate && ([ "$RUN_SEED" -eq 1 ] && yarn backend:seed)