version: '3.3'
services:
    postgres:
        env_file:
            - ./env/.db.env
        ports:
            - '5432:5432'
        image: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
            interval: 30s
            timeout: 5s
            retries: 5

    pgadmin4:
        env_file:
            - ./env/.db.env
        ports:
            - '8080:80'
        image: dpage/pgadmin4

    migration:
        depends_on:
            postgres:
                condition: service_healthy
        build:
            dockerfile: Dockerfile.migration
        env_file:
            - ./env/.backend.env
    
    beth:
        depends_on:
            postgres:
                condition: service_healthy
            migration:
                condition: service_completed_successfully
        build:
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
            - '3000:3000'
        env_file:
            - ./env/.backend.env
            - ./env/.frontend.env